name: Flagship
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23659
title: Flagship
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#283952'
    - '#46ed78'
    - '#2c5457'
    - '#43dd74'
    - '#2e635b'
  brandStrength: 1
  lightness: 0.5685936720110476
  saturation: 0.8191669872030616
  rhythmicContrast: 0.788270658813417
purpose: []
