name: Flagship
favicon: null
layout_spectrum: 0.7557648946531117
typography_spectrum: 0.7085836911574006
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4781296707224101
  lightness: 0.5685936720110476
  saturation: 0.8191669872030616
  rhythmicContrast: 0.788270658813417
purpose: []
